### PR TITLE
Stage 1

### PR DESCRIPTION
**Pull request by irmo12**
Backend for final project. almost all code is from p15.
successfully deployed to api.newsexplorer.mooo.com on a gcp machine.

### CODE REVIEW

**Comment by adzhenalieva** [comment]
# Summary:
## Backend

### Performance Criteria
- [ ]  The repository contains all the necessary infrastructure files:
  - [x] `package.json`;
  - [x] `.editorconfig`;
  - [ ] `.eslintrc` required for extending the configuration of `airbnb-base`. It also contains the devDependencies needed for the linter to work correctly;
      _In the linter settings, there has to be only the `airbnb-base` module: https://snipboard.io/0ZcUHL.jpg_
  - [x] `.gitignore`. The `.gitignore` file contains at least a `node_modules` folder.
  - [ ] Additionally, an exception for `_id` is added in `.eslintrc`. The following rules are forbidden: `eslint-disable`, `eslint-disable-line`, and `eslint-disable-next-line`.
     _The linter settings must contain only an exception for an _id and 'next'. The other rules shouldn't be overridden_
- [ ]  There are no lint errors. When running `npx eslint .` they should be absent.
     _There are several linter errors: https://snipboard.io/3lThuX.jpg_
- [x]  The scripts section of the package.json file contains the following:
  - [x] An `npm run start` command that starts the server on `localhost:3000`.
  - [x] An `npm run dev` command that starts the server on `localhost:3000` with hot reloading.
- [ ]  The following routes function as described:
  - [x] A request to `GET /users/me` returns information about the user (email and name).
  - [ ] `POST /signup` creates a user with the data passed inside the request body.
     _It is impossible to save the user because of the error in the celebrate validation scheme. More detailed information will be provided in the `validation` section_
  - [x] `POST /signin` returns a JWT when the correct email and password are passed in the request body.
  - [ ] `GET /articles` returns all articles saved by the user.
       - _In order to get the data saved by the user you need to filter data by `owner` field, for example, https://snipboard.io/U6XVJs.jpg_
      - _The orFail() in this controller is redundant. If the user did not save articles, it is not an error_
  - [x] `POST /articles` creates an article with the data passed inside the request body.
  - [ ] `DELETE /articles/:articleId` deletes the saved article using `_id`.
      _the 'select: false' option should be deleted from the `owner` field, and the owner field should be returned. It will be impossible to check the article's owner without it_
- [x]  Users can't delete saved articles from other user profiles.
- [ ]  All routes are protected with authorization, except for `/signin` and `/signup`.
     _The middleware for handling an unknown route also should be protected with the auth middleware_
- [x]  User routes and article routes are described in separate files.
- [ ]  API errors are handled:
  - [x] Error status codes are used: 400, 401, 403, 404, 409, 500.
  - [ ] If something is wrong with the request, the server returns a response with an error message and a corresponding status.
       _In the middleware for handling an unknown route the error should be passed to the next: `app.use('*', (req, res, next) => next(new NotFound('Requested resource does not exist')));`_
  - [x] The error message matches its type.
  - [x] Asynchronous handlers end with a `catch()` block.
  - [x] The API does not return standard database or Node.js errors.
- [x]  Safe password storage has been implemented:
  - [x] Passwords are stored in a hashed form.
  - [x] The API does not return a password hash to the client.
- [ ]  Validation implemented correctly:
  - [ ] Requests are validated before being passed to the controller. The body and (where applicable) headers and parameters are checked against the corresponding schemas. If a request doesn't match the schema, the processing is not passed to the controller and the client receives a validation error.
      _The `name` field should be added to the 'signup' celebrate validation scheme, because the 'name' field is required_
  - [ ] Data is validated before being added to the database.
     _In the User model the default value for the 'name' field should be deleted, because it is required_
- [ ]  In production mode, the database address is taken from `process.env`.
    _The database address is hardcoded_
- [x]  The server can be accessed via HTTPS using the domain specified in README.md.
- [ ]  Storing the private key for creating a JWT is implemented correctly:
  - [ ] For the production build, it is stored in an `.env` file, and this file should not be added to Git.
     _The `.env` file should not be added to the git_
  - [x] In development mode (`process.env.NODE_ENV !== 'production'`), the code runs and works fine, and an error won't occur if there is no `.env` file present.

### Best Practices
- [ ]  All routes are connected to the `index.js` file, which is located in the `routes` folder, and `app.js` contains one main route handled by routes.
- [x]  Asynchronous operations are implemented using promises or async/await.
- [ ]  Validation is described in a separate module.
- [x]  Logging is set up:
  - [x] All requests and responses are logged to the `request.log` file.
  - [x] All errors are logged to the `error.log` file.
  - [x] Log files aren't added to the git repository.
- [x]  Errors are handled by a centralized handler.
- [x]  Centralized error handling is described inside a separate module.
- [x]  The application API is located in an /api subdirectory or on an api. subdomain (not just name.zone)
  - [ ] Correct:  domain-name.tk/api or api.domain-name.tk
  - [x] Incorrect: domain-name.tk


### Recommendations
- [x]  For API errors, classes have been created to extend the Error constructor.
- [ ]  The Helmet module is used to set security-related headers.
- [ ]  Configuration and constants are stored in separate files:
  - [ ] The Mongo server address and the private key for the JWT in development mode are stored inside a separate configuration file.
  - [ ] Application constants (response and error messages) are stored inside a separate file with constants.
- [x]  A rate limiter is set up: the number of requests from a single IP address is limited to a particular value in a given amount of time.
- [x]  The rate limiter is configured in a separate file and imported into `app.js`.

## Number of points: 32

## Additional comments:
- These modules are redundant eslint-config-airbnb, eslint-plugin-jsx-a11y, eslint-plugin-react, eslint-plugin-react-hooks. They should be deleted

**Comment by irmo12** [comment]
thank you, Adzhenalieva,
linting problems: when i use destructuring i get no-undef, when i declare, it says prefer destructuring.

**Comment by irmo12** [comment]
all done.

**Comment by adzhenalieva** [comment]
# Summary:
## Backend

### Performance Criteria
- [ ]  The repository contains all the necessary infrastructure files:
  - [x] `package.json`;
  - [x] `.editorconfig`;
  - [ ] `.eslintrc` required for extending the configuration of `airbnb-base`. It also contains the devDependencies needed for the linter to work correctly;
      _The "eslint-config-airbnb-base" module should be added to the list of devDependencies. In the linter settings the redundant module should be deleted: https://snipboard.io/cFH6um.jpg_
  - [x] `.gitignore`. The `.gitignore` file contains at least a `node_modules` folder.
  - [x] Additionally, an exception for `_id` is added in `.eslintrc`. The following rules are forbidden: `eslint-disable`, `eslint-disable-line`, and `eslint-disable-next-line`.
- [ ]  There are no lint errors. When running `npx eslint .` they should be absent.
     _There is one linter error: https://snipboard.io/TV3qgC.jpg_
- [x]  The scripts section of the package.json file contains the following:
  - [x] An `npm run start` command that starts the server on `localhost:3000`.
  - [x] An `npm run dev` command that starts the server on `localhost:3000` with hot reloading.
- [ ]  The following routes function as described:
  - [x] A request to `GET /users/me` returns information about the user (email and name).
  - [ ] `POST /signup` creates a user with the data passed inside the request body.
     _It is impossible to save the user because the actual title of the field is `name`, not 'userName', the redundant 'catch' block should be deleted: https://snipboard.io/tmDHY3.jpg_
  - [x] `POST /signin` returns a JWT when the correct email and password are passed in the request body.
  - [ ] `GET /articles` returns all articles saved by the user.
       - _In order to get the data saved by the user you need to filter data by `owner` field, for example, https://snipboard.io/U6XVJs.jpg_
      - _The orFail() in this controller is redundant. If the user did not save articles, it is not an error_
  - [x] `POST /articles` creates an article with the data passed inside the request body.
  - [x] `DELETE /articles/:articleId` deletes the saved article using `_id`.
- [x]  Users can't delete saved articles from other user profiles.
- [x]  All routes are protected with authorization, except for `/signin` and `/signup`.
- [x]  User routes and article routes are described in separate files.
- [x]  API errors are handled:
  - [x] Error status codes are used: 400, 401, 403, 404, 409, 500.
  - [x] If something is wrong with the request, the server returns a response with an error message and a corresponding status.
  - [x] The error message matches its type.
  - [x] Asynchronous handlers end with a `catch()` block.
  - [x] The API does not return standard database or Node.js errors.
- [x]  Safe password storage has been implemented:
  - [x] Passwords are stored in a hashed form.
  - [x] The API does not return a password hash to the client.
- [ ]  Validation implemented correctly:
  - [ ] Requests are validated before being passed to the controller. The body and (where applicable) headers and parameters are checked against the corresponding schemas. If a request doesn't match the schema, the processing is not passed to the controller and the client receives a validation error.
      _The 'userName' should be changed to `name` in the celebrate validation scheme, because according to the task, the field is 'name'_
  - [x] Data is validated before being added to the database.
- [x]  In production mode, the database address is taken from `process.env`.
- [x]  The server can be accessed via HTTPS using the domain specified in README.md.
- [x]  Storing the private key for creating a JWT is implemented correctly:
  - [x] For the production build, it is stored in an `.env` file, and this file should not be added to Git.
  - [x] In development mode (`process.env.NODE_ENV !== 'production'`), the code runs and works fine, and an error won't occur if there is no `.env` file present.

### Best Practices
- [ ]  All routes are connected to the `index.js` file, which is located in the `routes` folder, and `app.js` contains one main route handled by routes.
- [x]  Asynchronous operations are implemented using promises or async/await.
- [ ]  Validation is described in a separate module.
- [x]  Logging is set up:
  - [x] All requests and responses are logged to the `request.log` file.
  - [x] All errors are logged to the `error.log` file.
  - [x] Log files aren't added to the git repository.
- [x]  Errors are handled by a centralized handler.
- [x]  Centralized error handling is described inside a separate module.
- [x]  The application API is located in an /api subdirectory or on an api. subdomain (not just name.zone)
  - [ ] Correct:  domain-name.tk/api or api.domain-name.tk
  - [x] Incorrect: domain-name.tk


### Recommendations
- [x]  For API errors, classes have been created to extend the Error constructor.
- [ ]  The Helmet module is used to set security-related headers.
- [ ]  Configuration and constants are stored in separate files:
  - [ ] The Mongo server address and the private key for the JWT in development mode are stored inside a separate configuration file.
  - [ ] Application constants (response and error messages) are stored inside a separate file with constants.
- [x]  A rate limiter is set up: the number of requests from a single IP address is limited to a particular value in a given amount of time.
- [x]  The rate limiter is configured in a separate file and imported into `app.js`.

## Number of points: 57

## Additional comments:
-  The database address should be set to the default value so that when run in dev mode, the code can run and work without an '.env' file
- Please, do not forget to update the deployed server, it still returns the errors from the first review

**Comment by adzhenalieva** [comment]
# Summary:
## Backend

### Performance Criteria
- [ ]  The repository contains all the necessary infrastructure files:
  - [x] `package.json`;
  - [x] `.editorconfig`;
  - [ ] `.eslintrc` required for extending the configuration of `airbnb-base`. It also contains the devDependencies needed for the linter to work correctly;
      _The "eslint-config-airbnb-base" module should be added to the list of devDependencies._
  - [x] `.gitignore`. The `.gitignore` file contains at least a `node_modules` folder.
  - [x] Additionally, an exception for `_id` is added in `.eslintrc`. The following rules are forbidden: `eslint-disable`, `eslint-disable-line`, and `eslint-disable-next-line`.
- [x]  There are no lint errors. When running `npx eslint .` they should be absent.
- [x]  The scripts section of the package.json file contains the following:
  - [x] An `npm run start` command that starts the server on `localhost:3000`.
  - [x] An `npm run dev` command that starts the server on `localhost:3000` with hot reloading.
- [ ]  The following routes function as described:
  - [x] A request to `GET /users/me` returns information about the user (email and name).
  - [ ] `POST /signup` creates a user with the data passed inside the request body.
     _It is impossible to save the user because the actual title of the field is `name`, not 'userName', the password field should be in braces: https://snipboard.io/l5Lvsh.jpg_
  - [x] `POST /signin` returns a JWT when the correct email and password are passed in the request body.
  - [ ] `GET /articles` returns all articles saved by the user.
      - _The orFail() in this controller is redundant. If the user did not save articles, it is not an error_
  - [x] `POST /articles` creates an article with the data passed inside the request body.
  - [x] `DELETE /articles/:articleId` deletes the saved article using `_id`.
- [x]  Users can't delete saved articles from other user profiles.
- [x]  All routes are protected with authorization, except for `/signin` and `/signup`.
- [x]  User routes and article routes are described in separate files.
- [x]  API errors are handled:
  - [x] Error status codes are used: 400, 401, 403, 404, 409, 500.
  - [x] If something is wrong with the request, the server returns a response with an error message and a corresponding status.
  - [x] The error message matches its type.
  - [x] Asynchronous handlers end with a `catch()` block.
  - [x] The API does not return standard database or Node.js errors.
- [x]  Safe password storage has been implemented:
  - [x] Passwords are stored in a hashed form.
  - [x] The API does not return a password hash to the client.
- [x]  Validation implemented correctly:
  - [x] Requests are validated before being passed to the controller. The body and (where applicable) headers and parameters are checked against the corresponding schemas. If a request doesn't match the schema, the processing is not passed to the controller and the client receives a validation error.
  - [x] Data is validated before being added to the database.
- [x]  In production mode, the database address is taken from `process.env`.
- [x]  The server can be accessed via HTTPS using the domain specified in README.md.
- [x]  Storing the private key for creating a JWT is implemented correctly:
  - [x] For the production build, it is stored in an `.env` file, and this file should not be added to Git.
  - [x] In development mode (`process.env.NODE_ENV !== 'production'`), the code runs and works fine, and an error won't occur if there is no `.env` file present.

### Best Practices
- [ ]  All routes are connected to the `index.js` file, which is located in the `routes` folder, and `app.js` contains one main route handled by routes.
- [x]  Asynchronous operations are implemented using promises or async/await.
- [ ]  Validation is described in a separate module.
- [x]  Logging is set up:
  - [x] All requests and responses are logged to the `request.log` file.
  - [x] All errors are logged to the `error.log` file.
  - [x] Log files aren't added to the git repository.
- [x]  Errors are handled by a centralized handler.
- [x]  Centralized error handling is described inside a separate module.
- [x]  The application API is located in an /api subdirectory or on an api. subdomain (not just name.zone)
  - [x] Correct:  domain-name.tk/api or api.domain-name.tk
  - [x] Incorrect: domain-name.tk


### Recommendations
- [x]  For API errors, classes have been created to extend the Error constructor.
- [ ]  The Helmet module is used to set security-related headers.
- [ ]  Configuration and constants are stored in separate files:
  - [ ] The Mongo server address and the private key for the JWT in development mode are stored inside a separate configuration file.
  - [ ] Application constants (response and error messages) are stored inside a separate file with constants.
- [x]  A rate limiter is set up: the number of requests from a single IP address is limited to a particular value in a given amount of time.
- [x]  The rate limiter is configured in a separate file and imported into `app.js`.

## Number of points: 68

## Additional comments:
-

**Comment by adzhenalieva** [comment]
# Summary:
## Backend

### Performance Criteria
- [x]  The repository contains all the necessary infrastructure files:
  - [x] `package.json`;
  - [x] `.editorconfig`;
  - [x] `.eslintrc` required for extending the configuration of `airbnb-base`. It also contains the devDependencies needed for the linter to work correctly;
  - [x] `.gitignore`. The `.gitignore` file contains at least a `node_modules` folder.
  - [x] Additionally, an exception for `_id` is added in `.eslintrc`. The following rules are forbidden: `eslint-disable`, `eslint-disable-line`, and `eslint-disable-next-line`.
- [x]  There are no lint errors. When running `npx eslint .` they should be absent.
- [x]  The scripts section of the package.json file contains the following:
  - [x] An `npm run start` command that starts the server on `localhost:3000`.
  - [x] An `npm run dev` command that starts the server on `localhost:3000` with hot reloading.
- [x]  The following routes function as described:
  - [x] A request to `GET /users/me` returns information about the user (email and name).
  - [x] `POST /signup` creates a user with the data passed inside the request body.
  - [x] `POST /signin` returns a JWT when the correct email and password are passed in the request body.
  - [xx] `GET /articles` returns all articles saved by the user.
  - [x] `POST /articles` creates an article with the data passed inside the request body.
  - [x] `DELETE /articles/:articleId` deletes the saved article using `_id`.
- [x]  Users can't delete saved articles from other user profiles.
- [x]  All routes are protected with authorization, except for `/signin` and `/signup`.
- [x]  User routes and article routes are described in separate files.
- [x]  API errors are handled:
  - [x] Error status codes are used: 400, 401, 403, 404, 409, 500.
  - [x] If something is wrong with the request, the server returns a response with an error message and a corresponding status.
  - [x] The error message matches its type.
  - [x] Asynchronous handlers end with a `catch()` block.
  - [x] The API does not return standard database or Node.js errors.
- [x]  Safe password storage has been implemented:
  - [x] Passwords are stored in a hashed form.
  - [x] The API does not return a password hash to the client.
- [x]  Validation implemented correctly:
  - [x] Requests are validated before being passed to the controller. The body and (where applicable) headers and parameters are checked against the corresponding schemas. If a request doesn't match the schema, the processing is not passed to the controller and the client receives a validation error.
  - [x] Data is validated before being added to the database.
- [x]  In production mode, the database address is taken from `process.env`.
- [x]  The server can be accessed via HTTPS using the domain specified in README.md.
- [x]  Storing the private key for creating a JWT is implemented correctly:
  - [x] For the production build, it is stored in an `.env` file, and this file should not be added to Git.
  - [x] In development mode (`process.env.NODE_ENV !== 'production'`), the code runs and works fine, and an error won't occur if there is no `.env` file present.

### Best Practices
- [ ]  All routes are connected to the `index.js` file, which is located in the `routes` folder, and `app.js` contains one main route handled by routes.
- [x]  Asynchronous operations are implemented using promises or async/await.
- [ ]  Validation is described in a separate module.
- [x]  Logging is set up:
  - [x] All requests and responses are logged to the `request.log` file.
  - [x] All errors are logged to the `error.log` file.
  - [x] Log files aren't added to the git repository.
- [x]  Errors are handled by a centralized handler.
- [x]  Centralized error handling is described inside a separate module.
- [x]  The application API is located in an /api subdirectory or on an api. subdomain (not just name.zone)
  - [x] Correct:  domain-name.tk/api or api.domain-name.tk
  - [x] Incorrect: domain-name.tk


### Recommendations
- [x]  For API errors, classes have been created to extend the Error constructor.
- [ ]  The Helmet module is used to set security-related headers.
- [ ]  Configuration and constants are stored in separate files:
  - [ ] The Mongo server address and the private key for the JWT in development mode are stored inside a separate configuration file.
  - [ ] Application constants (response and error messages) are stored inside a separate file with constants.
- [x]  A rate limiter is set up: the number of requests from a single IP address is limited to a particular value in a given amount of time.
- [x]  The rate limiter is configured in a separate file and imported into `app.js`.

## Number of points: 94

## Additional comments:
-  The orFail() in the 'getArticles' controller is redundant. If the user did not save articles, it is not an error

**Pull request merged**
